# permissions for end users to view peopleapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: peopleapp-viewer-role
rules:
- apiGroups:
  - people.omer.com.omer.com
  resources:
  - peopleapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - people.omer.com.omer.com
  resources:
  - peopleapps/status
  verbs:
  - get
