# permissions for end users to edit peopleapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: peopleapp-editor-role
rules:
- apiGroups:
  - api.peopleapp.io
  resources:
  - peopleapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.peopleapp.io
  resources:
  - peopleapps/status
  verbs:
  - get
